config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'

  # SESSION ROUTES
  post "/sessions" => "sessions#create", as: "login"
  delete "/session/:id" => "sessions#destroy", as: "logout"

  # USER ROUTES
  post "/users" => "users#create", as: "register"
  get "/users/:id" => "users#show", as: "user"

  # ATTENDEE ROUTES
  post "/playlists" => "playlists#create", as: "add_playlist"

  # SONG ROUTES
  get "/songs" => "songs#index", as: "songs"
  post "/songs" => "songs#create", as: "create_song"
  get "/songs/:id" => "songs#show", as: "song"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_many :playlists
  has_many :playlists_added_to, through: :playlists, source: :user

  validates :artist, :title, presence: :true
  validates :artist, length:{minimum:2}
  validates :title, length:{minimum:2}

  before_save :input_format
  def input_format
    self.artist.downcase!
    self.title.downcase!
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :songs
  has_many :playlists
  has_many :songs_added, through: :playlists, source: :song



  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  validates :fname, :lname, presence: :true

  before_save :input_format

  def input_format
    self.email.downcase!
    self.fname.downcase!
    self.lname.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login, except: [:index]

  def index
  end

  def require_login
    return redirect_to root_path unless session[:user_id]
  end
  def current_user
    # ONLY USE THIS IF YOU ARE NEEDING THE FULL USER INFO (name, email, etc) if you are going for an id, just use session[:user_id]
    return User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  helper_method :require_login
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def create
    Playlist.create(playlist_params)
    redirect_to songs_path
  end
  private
    def playlist_params
      params.require(:playlist).permit(:song_id).merge(user: current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def create
    user = User.find_by(email: params[:email])
    # find by email
    if user
      if user.try(:authenticate, params[:password])
        # if the user matches a user in the database, set the session id to the user being authenticated
        session[:user_id] = user.id
        return redirect_to songs_path
      end
      flash[:errors] = ["Invalid password"]
    else
      flash[:errors] = ["Invalid email"]
    end
    return redirect_back fallback_location: root_path
  end
  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end
  def show
    @song = Song.find(params[:id])
    @users = User.all
  end
  def create
    song = Song.create(song_params)

    if song.valid?
      return redirect_to songs_path
    else
      flash[:errors] = song.errors.full_messages
      return redirect_back fallback_location: songs_path
    end
  end
  private
    def song_params
      params.require(:song).permit(:artist, :title).merge(user: current_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:create]
  def create
    user = User.create(user_params)
    if user.valid?
      session[:user_id] = user.id
      return redirect_to songs_path
    else
      flash[:errors] = user.errors.full_messages
      return redirect_back fallback_location: root_path
    end
  end
  def show
    @user = User.find(params[:id])
    @songs = Song.all
  end
  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<h1>Register</h1>
<form action="<%= register_path %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>First Name</p>
  <input type="text" id="fname"name="user[fname]">
  <p>Last Name</p>
  <input type="text" id="lname"name="user[lname]">
  <p>Email</p>
  <input type="email" id="email"name="user[email]">
  <p>Password</p>
  <input type="password" id="password"name="user[password]">
  <p>Password Confirmation</p>
  <input type="password" id="password_confirmation"name="user[password_confirmation]">
  <button type="submit" name="button">Register</button>
</form>

<hr>

<h1>Login</h1>
<form action="<%= login_path %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Email</p>
  <input type="email" name = "email">
  <p>Password</p>
  <input type="password" name = "password">
  <button type="submit" name="login">Login</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeltOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if current_user %>
      <a href="<%= logout_path current_user.id %>" data-method="delete">Logout</a>
      |
      <a href="<%= songs_path %>">Songs Dashboard</a>
      <% end %>

    </nav>
    <div class="errors">
      <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
      <p><%= error %></p>
      <% end %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<h1>Welcome, <%= current_user.fname %>!</h1>
<h3>All Available Songs:</h3>
<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th>Number of Times Added to a Playlist</th>
      <th>Add to My Playlist</th>
    </tr>
  </thead>
  <tbody>
    <% for song in @songs %>
    <tr>
      <td><%= song.artist.titleize %></td>
      <td><a href="<%= song_path song.id %>"><%= song.title.titleize %></a></td>
      <td><%= song.playlists_added_to.count %></td>
      <td>
        <form action="<%= add_playlist_path %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="playlist[song_id]" value="<%= song.id %>">
          <input type="submit" name="Add" value="Add to Playlist">
        </form>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h1>Add a Song to the Database</h1>
<form action="<%= create_song_path %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <p>Artist</p>
  <input type="text" name="song[artist]">
  <p>Song Title</p>
  <input type="text" name="song[title]">
  <button type="submit" name="createsong">Add Song</button>
</form>

app/views/songs/show.html.erb
<h1>Other users who added <%= @song.artist.titleize %> - <%= @song.title.titleize %></h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Times Added</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
    <tr>
      <td> <a href="<%= user_path u.id %>"><%= u.fname.capitalize %> <%= u.lname.capitalize %></a></td>
      <td><%= u.songs_added.where(artist:@song.artist).count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.fname.capitalize %> <%= @user.lname.capitalize %>'s Playlist</h1>
<table>
  <thead>
    <tr>
      <th>Artist</th>
      <th>Title</th>
      <th>Times Added</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |s| %>
      <tr>
        <td><%= s.artist.titleize %></td>
        <td><%= s.title.titleize %></td>
        <td><%= s.playlists_added_to.where(fname:@user.fname).count %></td>
      </tr>
    <% end %>
  </tbody>
</table>